import type { ChiefComplaintId, AdaptiveQuestion } from '../types/clinical';

export const COMPLAINT_QUESTIONS_MAP: Record<ChiefComplaintId, AdaptiveQuestion[]> = {
  chest_pain: [
    {
      id: 'cp_duration',
      category: 'duration',
      type: 'select',
      text: {
        hi: 'सीने में दर्द कब से शुरू हुआ है?',
        en: 'When did the chest pain start?',
        bn: 'বুকে ব্যথা কখন থেকে শুরু হয়েছে?',
        mr: 'छातीत दुखणे कधीपासून सुरू झाले आहे?',
        te: 'ఛాతీ నొప్పి ఎప్పుడు ప్రారంభమైంది?',
        ta: 'நெஞ்சு வலி எப்போது தொடங்கியது?',
          pa: 'When did the chest pain start?',
  },
      options: [
        {
          id: 'acute_hours',
          label: {
            hi: 'पिछले 1 से 4 घंटे के भीतर (अचानक शुरू हुआ)',
            en: 'Within the last 1-4 hours (Sudden onset)',
            bn: 'গত ১-৪ ঘণ্টার মধ্যে (হঠাৎ শুরু)',
            mr: 'गेल्या १-४ तासांत (अचानक सुरू)',
            te: 'గత 1-4 గంటల్లో (అకస్మాత్తుగా)',
            ta: 'கடந்த 1-4 மணி நேரத்திற்குள் (திடீரென)',
                pa: 'Within the last 1-4 hours (Sudden onset)',
    },
          isRedFlag: true,
        },
        {
          id: 'subacute_days',
          label: {
            hi: '1 से 3 दिनों से आ-जा रहा है',
            en: 'Coming and going for 1-3 days',
            bn: '১-৩ দিন ধরে আসা-যাওয়া করছে',
            mr: '१-३ दिवसांपासून कमी-जास्त होत आहे',
            te: '1-3 రోజులుగా వస్తూ పోతోంది',
            ta: '1-3 நாட்களாக வந்து போகிறது',
                pa: 'Coming and going for 1-3 days',
    },
        },
        {
          id: 'chronic_weeks',
          label: {
            hi: 'कई हफ्तों या महीनों से केवल चलने पर होता है',
            en: 'For weeks/months only when walking or climbing stairs',
            bn: 'কয়েক সপ্তাহ/মাস ধরে কেবল হাঁটলে হয়',
            mr: 'काही आठवड्यांपासून फक्त चालताना होते',
            te: 'కొన్ని వారాలుగా నడిచినప్పుడు మాత్రమే',
            ta: 'பல வாரங்களாக நடக்கும் போது மட்டும்',
                pa: 'For weeks/months only when walking or climbing stairs',
    },
        },
      ],
    },
    {
      id: 'cp_character',
      category: 'character',
      type: 'select',
      text: {
        hi: 'दर्द किस प्रकार का महसूस हो रहा है?',
        en: 'How would you describe the chest pain?',
        bn: 'ব্যথাটা কেমন ধরনের মনে হচ্ছে?',
        mr: 'वेदना कशा प्रकारची जाणवत आहे?',
        te: 'నొప్పి ఏ విధంగా అనిపిస్తోంది?',
        ta: 'வலி எந்த மாதிரி உணர்கிறது?',
          pa: 'How would you describe the chest pain?',
  },
      options: [
        {
          id: 'crushing_pressure',
          label: {
            hi: 'भारी पत्थर जैसा दबाव या सीने में तेज जकड़न (Crushing Heaviness)',
            en: 'Crushing heavy pressure / tight squeezing sensation',
            bn: 'বুকে ভারী পাথরের মতো চাপ বা প্রচণ্ড আঁটসাঁট অনুভূতি',
            mr: 'छातीवर जड वजन किंवा दाबल्यासारखे वाटणे',
            te: 'ఛాతీపై బరువైన రాయి పెట్టినట్లుగా నలిపివేసే నొప్పి',
            ta: 'நெஞ்சில் பாரமான அழுத்தம் / பிசையும் உணர்வு',
                pa: 'Crushing heavy pressure / tight squeezing sensation',
    },
          isRedFlag: true,
        },
        {
          id: 'burning',
          label: {
            hi: 'सीने में जलन या खट्टी डकारें (Burning / Acidity)',
            en: 'Burning sensation in the center / acid reflux',
            bn: 'বুকে জ্বালাপোড়া বা অম্লভাব',
            mr: 'छातीत जळजळ किंवा ॲसिडिटी',
            te: 'ఛాతీలో మంట / ఎసిడిటీ',
            ta: 'நெஞ்செரிச்சல் / அசிடிட்டி',
                pa: 'Burning sensation in the center / acid reflux',
    },
        },
        {
          id: 'sharp_breathing',
          label: {
            hi: 'सुई जैसा चुभने वाला दर्द जो सांस लेने पर बढ़ता है',
            en: 'Sharp pricking pain that worsens on deep breathing or coughing',
            bn: 'ছুঁচ ফোটানোর মতো ব্যথা যা শ্বাস নিলে বাড়ে',
            mr: 'सुई टोचल्यासारखे दुखणे जे श्वास घेतल्यावर वाढते',
            te: 'సూది గుచ్చినట్లుగా ఊపిరి తీసుకుంటే ఎక్కువయ్యే నొప్పి',
            ta: 'ஊசி குத்துவது போன்ற வலி (மூச்சு விடும் போது கூடும்)',
                pa: 'Sharp pricking pain that worsens on deep breathing or coughing',
    },
        },
      ],
    },
    {
      id: 'cp_radiation',
      category: 'radiation',
      type: 'select',
      text: {
        hi: 'क्या यह दर्द सीने से कहीं और फैल रहा है?',
        en: 'Does the pain spread or radiate anywhere else?',
        bn: 'ব্যথা কি বুক থেকে অন্য কোথাও ছড়িয়ে পড়ছে?',
        mr: 'हा त्रास छातीतून इतरत्र कुठे पसरत आहे का?',
        te: 'ఈ నొప్పి ఛాతీ నుండి మరెక్కడికైనా వ్యాపిస్తోందా?',
        ta: 'இந்த வலி நெஞ்சிலிருந்து வேறு எங்காவது பரவுகிறதா?',
          pa: 'Does the pain spread or radiate anywhere else?',
  },
      options: [
        {
          id: 'rad_left_arm_jaw',
          label: {
            hi: 'हाँ, बाएं हाथ, जबड़े, गर्दन या पीठ की तरफ (Left Arm / Jaw)',
            en: 'Yes, radiates to Left Arm, Jaw, Neck or Back',
            bn: 'হ্যাঁ, বাম হাত, চোয়াল, ঘাড় বা পিঠের দিকে',
            mr: 'होय, डावा हात, जबडा, मान किंवा पाठीत',
            te: 'అవును, ఎడమ చేయి, దవడ, మెడ లేదా వీపుకు',
            ta: 'ஆம், இடது கை, தாடை, கழுத்து அல்லது முதுகுக்கு',
                pa: 'Yes, radiates to Left Arm, Jaw, Neck or Back',
    },
          isRedFlag: true,
        },
        {
          id: 'rad_none',
          label: {
            hi: 'नहीं, केवल सीने के एक हिस्से में ही है',
            en: 'No, localized to the chest only',
            bn: 'না, কেবল বুকের এক জায়গাতেই সীমাবদ্ধ',
            mr: 'नाही, फक्त छातीतच आहे',
            te: 'లేదు, ఛాతీ వద్ద మాత్రమే ఉంది',
            ta: 'இல்லை, நெஞ்சில் மட்டுமே உள்ளது',
                pa: 'No, localized to the chest only',
    },
        },
      ],
    },
    {
      id: 'cp_associated',
      category: 'associated',
      type: 'multiselect',
      text: {
        hi: 'इसके साथ और क्या परेशानियां हो रही हैं? (एक से अधिक चुन सकते हैं)',
        en: 'What other symptoms are you experiencing together with it?',
        bn: 'এর সাথে আর কী কী সমস্যা হচ্ছে?',
        mr: 'यासोबत आणखी काय त्रास होत आहे?',
        te: 'దీనితో పాటు మీకు ఇంకా ఏ సమస్యలు ఉన్నాయి?',
        ta: 'இதனுடன் வேறு என்ன அறிகுறிகள் உள்ளன?',
          pa: 'What other symptoms are you experiencing together with it?',
  },
      options: [
        {
          id: 'assoc_cold_sweats',
          label: {
            hi: 'ठंडा पसीना आना (Cold Sweating)',
            en: 'Profuse cold sweating (Diaphoresis)',
            bn: 'ঠান্ডা ঘাম হওয়া',
            mr: 'गार घाम येणे',
            te: 'చల్లని చెమటలు పట్టడం',
            ta: 'குளிர்ந்த வியர்வை கொட்டுதல்',
                pa: 'Profuse cold sweating (Diaphoresis)',
    },
          isRedFlag: true,
        },
        {
          id: 'assoc_sob',
          label: {
            hi: 'सांस फूलना या घबराहट (Breathlessness)',
            en: 'Shortness of breath / severe palpitations',
            bn: 'শ্বাসকষ্ট ও অস্থিরতা',
            mr: 'धाप लागणे किंवा धडधडणे',
            te: 'ఆయాసం లేదా దడ',
            ta: 'மூச்சுத்திணறல் / படபடப்பு',
                pa: 'Shortness of breath / severe palpitations',
    },
          isRedFlag: true,
        },
        {
          id: 'assoc_nausea',
          label: {
            hi: 'उल्टी जैसा लगना या चक्कर (Nausea/Giddiness)',
            en: 'Nausea or feeling faint / dizzy',
            bn: 'বমি ভাব বা মাথা ঘোরা',
            mr: 'मळमळ किंवा चक्कर येणे',
            te: 'వికారం లేదా కళ్లు తిరగడం',
            ta: 'குமட்டல் அல்லது மயக்கம்',
                pa: 'Nausea or feeling faint / dizzy',
    },
        },
        {
          id: 'assoc_none',
          label: {
            hi: 'इनमें से कोई नहीं',
            en: 'None of these',
            bn: 'এগুলির কোনোটিই নয়',
            mr: 'यापैकी काहीही नाही',
            te: 'ఇవేవీ లేవు',
            ta: 'இதில் எதுவும் இல்லை',
                pa: 'None of these',
    },
        },
      ],
    },
  ],

  fever: [
    {
      id: 'fv_duration',
      category: 'duration',
      type: 'select',
      text: {
        hi: 'बुखार कितने दिनों से आ रहा है?',
        en: 'How many days have you had the fever?',
        bn: 'কত দিন ধরে জ্বর আসছে?',
        mr: 'ताप किती दिवसांपासून येत आहे?',
        te: 'జ్వరం ఎన్ని రోజులుగా వస్తోంది?',
        ta: 'எத்தனை நாட்களாக காய்ச்சல் அடிக்கிறது?',
          pa: 'How many days have you had the fever?',
  },
      options: [
        {
          id: 'fv_1_2_days',
          label: {
            hi: '1 से 2 दिन (शुरुआती)',
            en: '1-2 days (Recent onset)',
            bn: '১-২ দিন',
            mr: '१ ते २ दिवस',
            te: '1-2 రోజులు',
            ta: '1-2 நாட்கள்',
                pa: '1-2 days (Recent onset)',
    },
        },
        {
          id: 'fv_3_7_days',
          label: {
            hi: '3 से 7 दिन (लगातार तेज बुखार)',
            en: '3 to 7 days (High continuous fever)',
            bn: '৩ থেকে ৭ দিন',
            mr: '३ ते ७ दिवस',
            te: '3 నుండి 7 రోజులు',
            ta: '3 முதல் 7 நாட்கள்',
                pa: '3 to 7 days (High continuous fever)',
    },
        },
        {
          id: 'fv_gt_week',
          label: {
            hi: '7 दिनों से अधिक (लंबे समय से बुखार)',
            en: 'More than 7 days (Prolonged fever)',
            bn: '৭ দিনের বেশি সময় ধরে',
            mr: '७ दिवसांपेक्षा जास्त दिवस',
            te: 'వారం కంటే ఎక్కువ రోజులు',
            ta: '1 வாரத்திற்கு மேல்',
                pa: 'More than 7 days (Prolonged fever)',
    },
          isRedFlag: true,
        },
      ],
    },
    {
      id: 'fv_chills',
      category: 'character',
      type: 'select',
      text: {
        hi: 'क्या बुखार के समय तेज कंपकंपी या जोड़ों में असहनीय दर्द होता है?',
        en: 'Do you experience shaking chills or severe bone/joint breaking pain?',
        bn: 'জ্বরের সাথে কি তীব্র কাঁপুনি বা হাড়ভাঙা ব্যথা হয়?',
        mr: 'तापाच्या वेळी तीव्र थंडी वाजून येते का किंवा सांधे भयंकर दुखतात का?',
        te: 'జ్వరంతో పాటు తీవ్రమైన వణుకు లేదా కీళ్ల నొప్పులు ఉన్నాయా?',
        ta: 'காய்ச்சலின் போது நடுக்கம் அல்லது எலும்பு முறிவு போன்ற வலி உள்ளதா?',
          pa: 'Do you experience shaking chills or severe bone/joint breaking pain?',
  },
      options: [
        {
          id: 'fv_shaking_chills',
          label: {
            hi: 'हाँ, रजाई ओढ़ने पर भी तेज कंपकंपी और आंखों के पीछे दर्द (Dengue/Malaria suspected)',
            en: 'Yes, severe chills, rigors and pain behind eyes / joints',
            bn: 'হ্যাঁ, প্রচণ্ড কাঁপুনি এবং চোখের পেছনে ও গাঁটে তীব্র ব্যথা',
            mr: 'होय, तीव्र थंडी, हुडहुडी व डोळ्यांच्या मागे तीव्र वेदना',
            te: 'అవును, తీవ్రమైన వణుకు మరియు కళ్ల వెనుక నొప్పి',
            ta: 'ஆம், கடுமையான நடுக்கம் மற்றும் கண்களுக்குப் பின்னால் வலி',
                pa: 'Yes, severe chills, rigors and pain behind eyes / joints',
    },
          isRedFlag: true,
        },
        {
          id: 'fv_mild_warmth',
          label: {
            hi: 'हल्की गर्माहट और थकान रहती है',
            en: 'Mild warmth and body fatigue',
            bn: 'হালকা জ্বর ভাব ও ক্লান্তি',
            mr: 'अंगात बारीक ताप व थकवा जाणवतो',
            te: 'స్వల్ప జ్వరం మరియు నీరసం',
            ta: 'லேசான காய்ச்சல் மற்றும் சோர்வு',
                pa: 'Mild warmth and body fatigue',
    },
        },
      ],
    },
    {
      id: 'fv_warning_signs',
      category: 'red_flag',
      type: 'multiselect',
      text: {
        hi: 'क्या इनमें से कोई गंभीर लक्षण मौजूद है?',
        en: 'Do you notice any of these critical warning signs?',
        bn: 'এর মধ্যে কোনো বিপজ্জনক লক্ষণ কি দেখা গেছে?',
        mr: 'खालीलपैकी कोणतीही गंभीर लक्षणे दिसत आहेत का?',
        te: 'ఈ క్రింది ప్రమాదకర లక్షణాలు ఏమైనా ఉన్నాయా?',
        ta: 'பின்வரும் தீவிர எச்சரிக்கை அறிகுறிகள் ஏதேனும் உள்ளதா?',
          pa: 'Do you notice any of these critical warning signs?',
  },
      options: [
        {
          id: 'fv_bleeding_rash',
          label: {
            hi: 'मसूड़ों या नाक से खून आना / त्वचा पर लाल-काले चकत्ते (Bleeding signs)',
            en: 'Bleeding from gums/nose or tiny red skin spots (Petechiae)',
            bn: 'মাড়ি বা নাক দিয়ে রক্ত পড়া বা ত্বকে লালচে দাগ',
            mr: 'हिरड्या किंवा नाकातून रक्त येणे किंवा अंगावर लाल पुरळ',
            te: 'చిగుళ్ళు లేదా ముక్కు నుండి రక్తం కారడం లేదా చర్మంపై ఎర్రటి మచ్చలు',
            ta: 'ஈறுகள்/மூக்கிலிருந்து ரத்தம் வடிதல் அல்லது தோலில் சிவப்பு புள்ளிகள்',
                pa: 'Bleeding from gums/nose or tiny red skin spots (Petechiae)',
    },
          isRedFlag: true,
        },
        {
          id: 'fv_confusion',
          label: {
            hi: 'मरीज का होश खोना या बहकी-बहकी बातें करना (Altered consciousness)',
            en: 'Extreme lethargy, confusion, or unable to wake up properly',
            bn: 'অসংলগ্ন কথাবার্তা বা নিস্তেজ হয়ে পড়া',
            mr: 'अचेत होणे, भ्रम किंवा भलतेच बोलणे',
            te: 'స్పృహ తప్పడం లేదా అసంబద్ధంగా మాట్లాడటం',
            ta: 'சுயநினைவு மங்குதல் அல்லது குழப்பமான பேச்சு',
                pa: 'Extreme lethargy, confusion, or unable to wake up properly',
    },
          isRedFlag: true,
        },
        {
          id: 'fv_none',
          label: {
            hi: 'कोई गंभीर लक्षण नहीं है',
            en: 'None of these warning signs',
            bn: 'কোনো বিপজ্জনক লক্ষণ নেই',
            mr: 'यापैकी कोणतीही गंभीर लक्षणे नाहीत',
            te: 'ఈ లక్షణాలు ఏవీ లేవు',
            ta: 'எந்த தீவிர எச்சரிக்கை அறிகுறிகளும் இல்லை',
                pa: 'None of these warning signs',
    },
        },
      ],
    },
  ],

  breathing_difficulty: [
    {
      id: 'sob_onset',
      category: 'onset',
      type: 'select',
      text: {
        hi: 'सांस की तकलीफ कब बढ़ जाती है?',
        en: 'When does the breathing difficulty worsen?',
        bn: 'শ্বাসকষ্ট কখন বেড়ে যায়?',
        mr: 'श्वासाचा त्रास कधी वाढतो?',
        te: 'శ్వాస తీసుకోవడంలో ఇబ్బంది ఎప్పుడు తీవ్రమవుతుంది?',
        ta: 'மூச்சுத்திணறல் எப்போது அதிகமாகிறது?',
          pa: 'When does the breathing difficulty worsen?',
  },
      options: [
        {
          id: 'sob_at_rest',
          label: {
            hi: 'बैठे या लेटे रहने पर भी सांस फूलती है (At rest)',
            en: 'Even while resting or lying completely flat in bed',
            bn: 'বিশ্রামে থাকা অবস্থাতেও শ্বাস নিতে কষ্ট হয়',
            mr: 'बसल्या जागी किंवा झोपल्यावरही धाप लागते',
            te: 'విశ్రాంతిలో ఉన్నప్పుడు కూడా శ్వాస ఆడదు',
            ta: 'ஓய்வாக இருக்கும் போதும் படுக்கும் போதும் மூச்சிரைக்கிறது',
                pa: 'Even while resting or lying completely flat in bed',
    },
          isRedFlag: true,
        },
        {
          id: 'sob_on_walking',
          label: {
            hi: 'केवल थोड़ा चलने या सीढ़ियां चढ़ने पर',
            en: 'Only on brisk walking or climbing stairs',
            bn: 'কিছুটা হাঁটলে বা সিঁড়ি উঠলে',
            mr: 'फक्त चालताना किंवा जिना चढताना',
            te: 'నడిచినప్పుడు లేదా మెట్లు ఎక్కినప్పుడు మాత్రమే',
            ta: 'நடக்கும் போது அல்லது படிக்கட்டு ஏறும் போது மட்டும்',
                pa: 'Only on brisk walking or climbing stairs',
    },
        },
      ],
    },
    {
      id: 'sob_associated',
      category: 'associated',
      type: 'multiselect',
      text: {
        hi: 'क्या पैरों में सूजन या रात में सांस घुटने से आंख खुलती है?',
        en: 'Do you have swelling in your legs or wake up gasping at night?',
        bn: 'পায়ে কি ফোলা আছে বা রাতে দম আটকে ঘুম ভাঙে?',
        mr: 'पायांवर सूज आहे का किंवा रात्री श्वास कोंडून जाग येते का?',
        te: 'కాళ్లలో వాపు ఉందా లేదా రాత్రిపూట ఊపిరాడక మెలకువ వస్తుందా?',
        ta: 'கால்களில் வீக்கம் உள்ளதா அல்லது இரவில் மூச்சுத்திணறி முழிப்பு வருகிறதா?',
          pa: 'Do you have swelling in your legs or wake up gasping at night?',
  },
      options: [
        {
          id: 'sob_pedal_edema',
          label: {
            hi: 'हाँ, दोनों पैरों / टखनों में सूजन है (Swollen feet)',
            en: 'Yes, both feet/ankles are swollen',
            bn: 'হ্যাঁ, দুই পায়েই ফোলা আছে',
            mr: 'होय, दोन्ही पायांवर सूज आहे',
            te: 'అవును, రెండు కాళ్లలో వాపు ఉంది',
            ta: 'ஆம், இரண்டு கால்களிலும் வீக்கம் உள்ளது',
                pa: 'Yes, both feet/ankles are swollen',
    },
          isRedFlag: true,
        },
        {
          id: 'sob_wheeze',
          label: {
            hi: 'सीने से सीटी जैसी आवाज (घरघराहट / दमा)',
            en: 'Whistling wheeze sound in chest / known asthma',
            bn: 'বুকে সাঁই-সাঁই বাঁশির মতো শব্দ',
            mr: 'छातीतून शिट्टीसारखा आवाज येतो',
            te: 'ఛాతీలో పిల్లికూతలు లేదా ఈల వంటి శబ్దం',
            ta: 'நெஞ்சில் விசில் சத்தம் / வீசிங்',
                pa: 'Whistling wheeze sound in chest / known asthma',
    },
        },
      ],
    },
  ],

  abdominal_pain: [
    {
      id: 'ab_location',
      category: 'character',
      type: 'select',
      text: {
        hi: 'पेट में दर्द मुख्य रूप से किस जगह पर है?',
        en: 'Where exactly is the abdominal pain located?',
        bn: 'পেটের কোন অংশে মূলত ব্যথা হচ্ছে?',
        mr: 'पोटात प्रामुख्याने कोणत्या भागात दुखत आहे?',
        te: 'కడుపులో ఖచ్చితంగా ఎక్కడ నొప్పి ఉంది?',
        ta: 'வயிற்றில் வலி சரியாக எங்கு உள்ளது?',
          pa: 'Where exactly is the abdominal pain located?',
  },
      options: [
        {
          id: 'ab_right_lower',
          label: {
            hi: 'निचले दाएं हिस्से में तेज असहनीय दर्द (Right Lower Abdomen - Appendix)',
            en: 'Severe sharp pain in the lower right side (Suspected Appendicitis)',
            bn: 'তলপেটের ডান দিকে তীব্র খোঁচা মারা ব্যথা',
            mr: 'उजव्या बाजूला खाली तीव्र असह्य वेदना',
            te: 'కడుపు కింది భాగంలో కుడివైపున తీవ్రమైన నొప్పి',
            ta: 'அடிவயிற்றின் வலது பக்கத்தில் கடுமையான வலி',
                pa: 'Severe sharp pain in the lower right side (Suspected Appendicitis)',
    },
          isRedFlag: true,
        },
        {
          id: 'ab_upper_center',
          label: {
            hi: 'ऊपरी पेट में छाती के ठीक नीचे जलन व दर्द',
            en: 'Upper center / below ribs burning pain (Gastritis / Gallbladder)',
            bn: 'উপরের পেটে জ্বালা ও অস্বস্তি',
            mr: 'वरच्या पोटात जळजळ आणि दुखणे',
            te: 'పై కడుపులో మంట మరియు నొప్పి',
            ta: 'மேல் வயிற்றில் எரிச்சல் மற்றும் வலி',
                pa: 'Upper center / below ribs burning pain (Gastritis / Gallbladder)',
    },
        },
        {
          id: 'ab_diffuse',
          label: {
            hi: 'पूरे पेट में मरोड़ और गैस',
            en: 'Generalized cramps and gas across entire belly',
            bn: 'পুরো পেটে মোচড় ও গ্যাস',
            mr: 'संपूर्ण पोटात गोळा येणे',
            te: 'మొత్తం కడుపులో తిమ్మిరి మరియు గ్యాస్',
            ta: 'முழு வயிற்றிலும் பிடிப்பு மற்றும் வாயு',
                pa: 'Generalized cramps and gas across entire belly',
    },
        },
      ],
    },
    {
      id: 'ab_red_flags',
      category: 'red_flag',
      type: 'multiselect',
      text: {
        hi: 'क्या उल्टी में खून, पेट का कड़ा (तख्त जैसा) होना या मल में खून आया है?',
        en: 'Any blood in vomit, rigid board-like belly, or black tarry stools?',
        bn: 'বমিতে রক্ত, পেট খুব শক্ত হওয়া বা কালো মলত্যাগ হয়েছে?',
        mr: 'उलटीत रक्त, पोट लाकडासारखे कडक होणे किंवा शौचात रक्त आले आहे का?',
        te: 'వాంతిలో రక్తం, కడుపు బండలా గట్టిపడటం లేదా మలంలో రక్తం పడిందా?',
        ta: 'வாந்தியில் ரத்தம், வயிறு மரக்கட்டை போல் இறுகுதல் அல்லது மலத்தில் ரத்தம் உள்ளதா?',
          pa: 'Any blood in vomit, rigid board-like belly, or black tarry stools?',
  },
      options: [
        {
          id: 'ab_bleed_rigid',
          label: {
            hi: 'हाँ, खून की उल्टी या पेट छूने पर असहनीय कड़ा है (Critical Surgical Alert)',
            en: 'Yes, blood in vomit/stool or rigid rock-hard abdomen',
            bn: 'হ্যাঁ, রক্তবমি অথবা পেট কাঠের মতো শক্ত',
            mr: 'होय, रक्ताची उलटी किंवा पोट अतिशय कडक झाले आहे',
            te: 'అవును, రక్తపు వాంతులు లేదా కడుపు బండలా గట్టిగా ఉంది',
            ta: 'ஆம், ரத்த வாந்தி அல்லது வயிறு மிகவும் கடினமாக உள்ளது',
                pa: 'Yes, blood in vomit/stool or rigid rock-hard abdomen',
    },
          isRedFlag: true,
        },
        {
          id: 'ab_none',
          label: {
            hi: 'नहीं, ऐसा कुछ नहीं है',
            en: 'No such critical symptoms',
            bn: 'না, এমন কোনো লক্ষণ নেই',
            mr: 'नाही, अशी कोणतीही गंभीर लक्षणे नाहीत',
            te: 'లేదు, అలాంటి లక్షణాలు లేవు',
            ta: 'இல்லை, அத்தகைய தீவிர அறிகுறிகள் இல்லை',
                pa: 'No such critical symptoms',
    },
        },
      ],
    },
  ],

  joint_pain: [
    {
      id: 'jp_joints',
      category: 'character',
      type: 'select',
      text: {
        hi: 'मुख्य रूप से कौन से जोड़ में तकलीफ है?',
        en: 'Which joints are primarily painful or swollen?',
        bn: 'প্রধানত কোন জয়েন্টে ব্যথা বা ফোলা রয়েছে?',
        mr: 'प्रामुख्याने कोणत्या सांध्यात जास्त त्रास आहे?',
        te: 'ప్రధానంగా ఏ కీళ్లలో నొప్పి లేదా వాపు ఉంది?',
        ta: 'முக்கியமாக எந்த மூட்டுகளில் வலி அல்லது வீக்கம் உள்ளது?',
          pa: 'Which joints are primarily painful or swollen?',
  },
      options: [
        {
          id: 'jp_knees',
          label: {
            hi: 'दोनों घुटनों में (उठने-बैठने में कट-कट आवाज / ऑस्टियोआर्थराइटिस)',
            en: 'Both knees (Crepitus, pain on standing / Osteoarthritis)',
            bn: 'দুই হাঁটুতে (ওঠাবসায় কষ্ট)',
            mr: 'दोन्ही गुडघ्यांत (उठताना-बसताना त्रास)',
            te: 'రెండు మోకాళ్లలో (కూర్చుని లేచేటప్పుడు శబ్దం/నొప్పి)',
            ta: 'இரண்டு முழங்கால்களிலும் (எழுந்து உட்காரும் போது வலி)',
                pa: 'Both knees (Crepitus, pain on standing / Osteoarthritis)',
    },
        },
        {
          id: 'jp_hands_morning',
          label: {
            hi: 'हाथ की उंगलियों में और सुबह उठने पर 1 घंटे से ज्यादा अकड़न (Rheumatoid Arthritis)',
            en: 'Small joints of hands with >1 hr morning stiffness',
            bn: 'হাতের আঙুলে এবং সকালে ওঠার পর প্রচণ্ড আড়ষ্টতা',
            mr: 'हातांच्या बोटांमध्ये व सकाळी तीव्र कडकपणा',
            te: 'చేతి వేళ్ల కీళ్లలో ఉదయం పూట బిగుసుకుపోవడం',
            ta: 'கை விரல் மூட்டுகளில் காலை நேர விறைப்பு',
                pa: 'Small joints of hands with >1 hr morning stiffness',
    },
        },
        {
          id: 'jp_single_hot_swollen',
          label: {
            hi: 'एक ही जोड़ अत्यधिक लाल, गर्म और छूने पर असहनीय दर्द (Septic/Gout)',
            en: 'Single joint acutely red, hot, swollen and tender (Gout/Septic)',
            bn: 'একটিমাত্র জয়েন্ট লাল, গরম ও ভীষণ ফোলা',
            mr: 'एकच सांधा लाल, गरम व भयंकर सुजलेला',
            te: 'ఒక్క కీలు మాత్రమే ఎర్రబడి, వేడిగా మరియు తీవ్ర వాపుతో ఉంది',
            ta: 'ஒரே ஒரு மூட்டு மட்டும் சிவந்து, சூடாகி கடுமையான வீக்கத்துடன் உள்ளது',
                pa: 'Single joint acutely red, hot, swollen and tender (Gout/Septic)',
    },
          isRedFlag: true,
        },
      ],
    },
  ],

  headache: [
    {
      id: 'ha_character',
      category: 'character',
      type: 'select',
      text: {
        hi: 'सिरदर्द की शुरुआत कैसे हुई?',
        en: 'How did the headache start and feel?',
        bn: 'মাথাব্যথা কীভাবে শুরু হয়েছিল?',
        mr: 'डोकेदुखी कशी सुरू झाली?',
        te: 'తలనొప్పి ఎలా ప్రారంభమైంది?',
        ta: 'தலைவலி எவ்வாறு தொடங்கியது?',
          pa: 'How did the headache start and feel?',
  },
      options: [
        {
          id: 'ha_thunderclap',
          label: {
            hi: 'जिंदगी का सबसे तेज सिरदर्द जो 1 मिनट में बिजली की तरह फटा (Thunderclap)',
            en: 'Worst headache of life, sudden explosion like a thunderclap',
            bn: 'জীবনের সবচেয়ে মারাত্মক মাথাব্যথা যা হঠাৎ শুরু হয়েছে',
            mr: 'जीवनातील सर्वात भयानक डोकेदुखी जी विजेसारखी अचानक सुरू झाली',
            te: 'జీవితంలో ఎన్నడూ లేనంత తీవ్రమైన తలనొప్పి అకస్మాత్తుగా రావడం',
            ta: 'வாழ்நாளில் இல்லாத மிகக் கடுமையான திடீர் தலைவலி',
                pa: 'Worst headache of life, sudden explosion like a thunderclap',
    },
          isRedFlag: true,
        },
        {
          id: 'ha_migraine',
          label: {
            hi: 'सिर के एक तरफ धड़कने वाला दर्द, रोशनी या आवाज से परेशानी (Migraine)',
            en: 'One-sided throbbing pain with nausea, sensitivity to light/sound',
            bn: 'মাথার একপাশে দপদপে ব্যথা ও বমি ভাব',
            mr: 'एका बाजूला ठणकणारे दुखणे व प्रकाशाचा त्रास',
            te: 'తల ఒక వైపు కొట్టుకునే నొప్పి, వెలుతురు చూడలేకపోవడం',
            ta: 'தலையின் ஒரு பக்க துடிப்பு வலி மற்றும் வெளிச்சம் பார்க்க முடியாமை',
                pa: 'One-sided throbbing pain with nausea, sensitivity to light/sound',
    },
        },
        {
          id: 'ha_tension',
          label: {
            hi: 'सिर के चारों तरफ भारी पट्टी जैसा तनाव और दबाव',
            en: 'Dull tight band around the head / neck heaviness',
            bn: 'মাথার চারপাশে ভারী চাপ বা টান',
            mr: 'डोक्याभोवती पट्टा बांधल्यासारखा जडपणा',
            te: 'తల చుట్టూ పట్టీ బిగించినట్లుగా బరువు',
            ta: 'தலையைச் சுற்றி பட்டை கட்டியது போன்ற பாரம்',
                pa: 'Dull tight band around the head / neck heaviness',
    },
        },
      ],
    },
    {
      id: 'ha_neuro',
      category: 'red_flag',
      type: 'multiselect',
      text: {
        hi: 'क्या इनमें से कोई न्यूरोलॉजिकल लक्षण है?',
        en: 'Do you have any of these neurological red flags?',
        bn: 'এর মধ্যে কোনো স্নায়বিক সমস্যা কি হচ্ছে?',
        mr: 'खालीलपैकी कोणतीही मेंदू/मज्जातंतू संबंधित लक्षणे आहेत का?',
        te: 'ఈ నరాల సంబంధిత ప్రమాదకర లక్షణాలు ఏమైనా ఉన్నాయా?',
        ta: 'நரம்பியல் தொடர்பான எச்சரிக்கை அறிகுறிகள் உள்ளதா?',
          pa: 'Do you have any of these neurological red flags?',
  },
      options: [
        {
          id: 'ha_weakness_speech',
          label: {
            hi: 'मुंह का टेढ़ा होना, बोलने में लड़खड़ाहट या एक हाथ-पैर में कमजोरी (Stroke Warning)',
            en: 'Facial droop, slurred speech, or weakness in one arm/leg (Stroke)',
            bn: 'মুখ বেঁকে যাওয়া, কথা জড়িয়ে যাওয়া বা হাত-পায়ে দুর্বলতা',
            mr: 'तोंड वाकडे होणे, बोलताना तोतरेपणा किंवा एका बाजूला अशक्तपणा',
            te: 'మూతి వంకరపోవడం, మాట ముద్ద రావడం లేదా ఒక చేయి/కాలు బలహీనపడటం',
            ta: 'வாய் ஒருபுறம் கோணுதல், பேச்சு குளறுதல் அல்லது ஒரு கை/கால் பலவீனம்',
                pa: 'Facial droop, slurred speech, or weakness in one arm/leg (Stroke)',
    },
          isRedFlag: true,
        },
        {
          id: 'ha_neck_stiff',
          label: {
            hi: 'गर्दन का अकड़ जाना और सिर नीचे झुकाने में तेज दर्द (Meningitis sign)',
            en: 'Stiff neck unable to touch chin to chest with fever',
            bn: 'ঘাড় শক্ত হয়ে যাওয়া ও চিবুক বুকে লাগাতে না পারা',
            mr: 'मान ताठ होणे व हनुवटी छातीला लावता न येणे',
            te: 'మెడ బిగుసుకుపోవడం మరియు గడ్డం ఛాతీకి ఆనించలేకపోవడం',
            ta: 'கழுத்து விறைத்து தாடையை மார்பில் தொட முடியாமை',
                pa: 'Stiff neck unable to touch chin to chest with fever',
    },
          isRedFlag: true,
        },
        {
          id: 'ha_none',
          label: {
            hi: 'कोई न्यूरोलॉजिकल लक्षण नहीं',
            en: 'None of these',
            bn: 'কোনো স্নায়বিক লক্ষণ নেই',
            mr: 'काहीही नाही',
            te: 'ఇలాంటివి ఏవీ లేవు',
            ta: 'எந்த தீவிர நரம்பியல் அறிகுறிகளும் இல்லை',
                pa: 'None of these',
    },
        },
      ],
    },
  ],

  vomiting_diarrhea: [
    {
      id: 'vd_frequency',
      category: 'duration',
      type: 'select',
      text: {
        hi: 'पिछले 24 घंटों में कितनी बार उल्टी या दस्त हुए हैं?',
        en: 'How many episodes of vomiting or loose motions in last 24 hours?',
        bn: 'গত ২৪ ঘণ্টায় কতবার বমি বা পাতলা পায়খানা হয়েছে?',
        mr: 'गेल्या २४ तासांत किती वेळा उलट्या किंवा जुलाब झाले?',
        te: 'గత 24 గంటల్లో ఎన్నిసార్లు వాంతులు లేదా విరేచనాలు అయ్యాయి?',
        ta: 'கடந்த 24 மணி நேரத்தில் எத்தனை முறை வாந்தி அல்லது வயிற்றுப்போக்கு ஏற்பட்டது?',
          pa: 'How many episodes of vomiting or loose motions in last 24 hours?',
  },
      options: [
        {
          id: 'vd_gt_8',
          label: {
            hi: '8 से 10 बार से अधिक (पानी भी नहीं पच रहा / गंभीर डिहाइड्रेशन)',
            en: 'More than 8-10 times, cannot keep even water down',
            bn: '৮-১০ বারের বেশি, জলও পেটে থাকছে না',
            mr: '८-१० पेक्षा जास्त वेळा, पाणीही पचत नाही',
            te: '8-10 సార్ల కంటే ఎక్కువ, మంచినీళ్లు కూడా తాగలేకపోతున్నారు',
            ta: '8-10 முறைக்கு மேல், தண்ணீர் கூட குடிக்க முடியவில்லை',
                pa: 'More than 8-10 times, cannot keep even water down',
    },
          isRedFlag: true,
        },
        {
          id: 'vd_3_5',
          label: {
            hi: '3 से 5 बार, ओआरएस या पानी ले पा रहे हैं',
            en: '3-5 times, able to drink ORS / fluids',
            bn: '৩-৫ বার, ওআরএস খেতে পারছেন',
            mr: '३ ते ५ वेळा, ओआरएस पाणी घेत आहेत',
            te: '3-5 సార్లు, ఓఆర్ఎస్ ద్రావణం తాగగలుగుతున్నారు',
            ta: '3-5 முறை, ஓஆர்எஸ் நீர் குடிக்க முடிகிறது',
                pa: '3-5 times, able to drink ORS / fluids',
    },
        },
      ],
    },
    {
      id: 'vd_urine',
      category: 'red_flag',
      type: 'select',
      text: {
        hi: 'क्या पिछले 8-10 घंटों से पेशाब बिल्कुल बंद या बहुत कम आई है?',
        en: 'Has urine output severely decreased or stopped for >8 hours?',
        bn: 'গত ৮-১০ ঘণ্টায় প্রস্রাব কি বন্ধ বা খুব কমে গেছে?',
        mr: 'गेल्या ८-१० तासांत लघवी पूर्ण बंद किंवा खूप कमी झाली आहे का?',
        te: 'గత 8-10 గంటలుగా మూత్రం పూర్తిగా ఆగిపోయిందా లేదా చాలా తగ్గిపోయిందా?',
        ta: 'கடந்த 8-10 மணி நேரமாக சிறுநீர் சுத்தமாக வரவில்லையா அல்லது மிகவும் குறைந்துவிட்டதா?',
          pa: 'Has urine output severely decreased or stopped for >8 hours?',
  },
      options: [
        {
          id: 'vd_anuria',
          label: {
            hi: 'हाँ, पेशाब बिल्कुल नहीं आई और अत्यधिक कमजोरी है (Acute Kidney / Shock Risk)',
            en: 'Yes, no urine passed for hours, extreme lethargy and dry mouth',
            bn: 'হ্যাঁ, প্রস্রাব একদম হয়নি ও প্রচণ্ড দুর্বলতা',
            mr: 'होय, लघवी अजिबात झाली नाही व अतिशय गळून गेले आहेत',
            te: 'అవును, మూత్రం రాలేదు మరియు తీవ్ర నిస్సత్తువ',
            ta: 'ஆம், சிறுநீர் வரவில்லை மற்றும் கடுமையான சோர்வு',
                pa: 'Yes, no urine passed for hours, extreme lethargy and dry mouth',
    },
          isRedFlag: true,
        },
        {
          id: 'vd_normal_urine',
          label: {
            hi: 'नहीं, सामान्य रूप से पेशाब आ रही है',
            en: 'No, passing urine regularly',
            bn: 'না, প্রস্রাব স্বাভাবিকভাবেই হচ্ছে',
            mr: 'नाही, लघवी व्यवस्थित होत आहे',
            te: 'లేదు, మూత్రం సాధారణంగానే వస్తోంది',
            ta: 'இல்லை, சிறுநீர் சாதாரணமாக வருகிறது',
                pa: 'No, passing urine regularly',
    },
        },
      ],
    },
  ],

  diabetes_review: [
    {
      id: 'dm_history',
      category: 'character',
      type: 'select',
      text: {
        hi: 'आपको डायबिटीज या हाई ब्लड प्रेशर कितने समय से है?',
        en: 'How long have you had Diabetes or High Blood Pressure?',
        bn: 'কতদিন ধরে ডায়াবেটিস বা উচ্চ রক্তচাপের সমস্যা আছে?',
        mr: 'मधुमेह किंवा उच्च रक्तदाब किती वर्षांपासून आहे?',
        te: 'మీకు డయాబెటిస్ లేదా హై బీపీ ఎంతకాలంగా ఉంది?',
        ta: 'எவ்வளவு காலமாக சர்க்கரை அல்லது ரத்த அழுத்தம் உள்ளது?',
          pa: 'How long have you had Diabetes or High Blood Pressure?',
  },
      options: [
        {
          id: 'dm_gt_10',
          label: {
            hi: '10 साल से अधिक समय से (Chronic Longstanding)',
            en: 'More than 10 years',
            bn: '১০ বছরের বেশি সময় ধরে',
            mr: '१० पेक्षा जास्त वर्षांपासून',
            te: '10 సంవత్సరాలకు పైగా',
            ta: '10 ஆண்டுகளுக்கு மேலாக',
                pa: 'More than 10 years',
    },
        },
        {
          id: 'dm_1_5_yr',
          label: {
            hi: '1 से 5 साल से',
            en: '1 to 5 years',
            bn: '১ থেকে ৫ বছর ধরে',
            mr: '१ ते ५ वर्षे',
            te: '1 నుండి 5 సంవత్సరాలు',
            ta: '1 முதல் 5 ஆண்டுகள்',
                pa: '1 to 5 years',
    },
        },
        {
          id: 'dm_new',
          label: {
            hi: 'हाल ही में पहली बार पता चला है',
            en: 'Newly suspected / recently detected',
            bn: 'সম্প্রতি নতুন ধরা পড়েছে',
            mr: 'नुकताच शोध लागला आहे',
            te: 'ఇటీవల కొత్తగా గుర్తించబడింది',
            ta: 'சமீபத்தில் புதிதாக கண்டறியப்பட்டது',
                pa: 'Newly suspected / recently detected',
    },
        },
      ],
    },
    {
      id: 'dm_symptoms',
      category: 'associated',
      type: 'multiselect',
      text: {
        hi: 'क्या पैरों में झुनझुनी, आंखों से धुंधला दिखना या कोई न भरने वाला घाव है?',
        en: 'Any tingling numbness in feet, blurred vision, or non-healing foot wound?',
        bn: 'পায়ে ঝিনঝিন, চোখে ঝাপসা দেখা বা পায়ে না সারা কোনো ঘা আছে?',
        mr: 'पायांना मुंग्या येणे, डोळ्यांनी अंधुक दिसणे किंवा न भरणारी जखम आहे का?',
        te: 'కాళ్లలో తిమ్మిర్లు, కంటిచూపు మసకబారడం లేదా మానని పుండు ఉందా?',
        ta: 'கால்களில் மரத்துப்போதல், கண் பார்வை மங்குதல் அல்லது ஆறாத புண் உள்ளதா?',
          pa: 'Any tingling numbness in feet, blurred vision, or non-healing foot wound?',
  },
      options: [
        {
          id: 'dm_foot_ulcer',
          label: {
            hi: 'हाँ, पैर या अंगूठे में घाव है जो भर नहीं रहा (Diabetic Foot Ulcer Alert)',
            en: 'Yes, non-healing foot sore / blackened toe (Diabetic Foot)',
            bn: 'হ্যাঁ, পায়ে ক্ষত বা ঘা যা সারছে না',
            mr: 'होय, पायात न भरणारी जखम आहे',
            te: 'అవును, కాలిపై మానని పుండు ఉంది',
            ta: 'ஆம், காலில் ஆறாத புண் உள்ளது',
                pa: 'Yes, non-healing foot sore / blackened toe (Diabetic Foot)',
    },
          isRedFlag: true,
        },
        {
          id: 'dm_neuropathy',
          label: {
            hi: 'पैरों के तलवों में जलन या सुई जैसी झुनझुनी (Neuropathy)',
            en: 'Burning sensation and tingling in soles (Neuropathy)',
            bn: 'পায়ের তলায় জ্বালা বা অসাড় ভাব',
            mr: 'तळपायांची जळजळ किंवा मुंग्या येणे',
            te: 'అరికాళ్లలో మంటలు లేదా తిమ్మిరి',
            ta: 'உள்ளங்காலில் எரிச்சல் அல்லது மரத்துப்போதல்',
                pa: 'Burning sensation and tingling in soles (Neuropathy)',
    },
        },
        {
          id: 'dm_none',
          label: {
            hi: 'कोई जटिलता नहीं, केवल नियमित दवा परामर्श चाहिए',
            en: 'No complications, just routine refill and checkup',
            bn: 'কোনো জটিলতা নেই, শুধুই নিয়মিত চেকআপ',
            mr: 'काही अडचण नाही, फक्त औषधे हवी आहेत',
            te: 'ఏ సమస్యలు లేవు, రెగ్యులర్ చెకప్ మాత్రమే',
            ta: 'எந்த சிக்கலும் இல்லை, வழக்கமான மாத்திரை மட்டும் போதும்',
                pa: 'No complications, just routine refill and checkup',
    },
        },
      ],
    },
  ],

  skin_rash: [
    {
      id: 'sk_type',
      category: 'character',
      type: 'select',
      text: {
        hi: 'चकत्ते या घाव का प्रकार कैसा है?',
        en: 'What kind of rash or lesion is it?',
        bn: 'ফুসকুড়ি বা চর্মরোগ কেমন ধরনের?',
        mr: 'पुरळ किंवा त्वचेचा आजार कसा आहे?',
        te: 'దద్దుర్లు లేదా చర్మ సమస్య ఏ రకమైనది?',
        ta: 'தோல் தடிப்பு அல்லது பிரச்சினை எத்தகையது?',
          pa: 'What kind of rash or lesion is it?',
  },
      options: [
        {
          id: 'sk_spreading_fever',
          label: {
            hi: 'तेजी से फैलती लालिमा, तेज दर्द व बुखार (Cellulitis / Erysipelas)',
            en: 'Rapidly spreading redness, severe pain, heat and fever (Cellulitis)',
            bn: 'দ্রুত ছড়িয়ে পড়া লালচে ভাব, তীব্র ব্যথা ও জ্বর',
            mr: 'वेगाने पसरणारा लालसरपणा, तीव्र वेदना व ताप',
            te: 'వేగంగా వ్యాపించే ఎరుపు రంగు, తీవ్ర నొప్పి మరియు జ్వరం',
            ta: 'வேகமாகப் பரவும் சிவத்தல், கடுமையான வலி மற்றும் காய்ச்சல்',
                pa: 'Rapidly spreading redness, severe pain, heat and fever (Cellulitis)',
    },
          isRedFlag: true,
        },
        {
          id: 'sk_itchy_chronic',
          label: {
            hi: 'पुरानी खुजली, सूखी पपड़ीदार त्वचा (Eczema/Fungal)',
            en: 'Chronic dry scaly patches, intense itching',
            bn: 'পুরনো চুলকানি ও খসখসে ত্বক',
            mr: 'जुनी खाज व कोरडी त्वचा',
            te: 'దీర్ఘకాలిక దురద మరియు పొడి చర్మం',
            ta: 'நீண்டகால அரிப்பு மற்றும் செதில் போன்ற தோல்',
                pa: 'Chronic dry scaly patches, intense itching',
    },
        },
      ],
    },
  ],

  general_weakness: [
    {
      id: 'gw_onset',
      category: 'onset',
      type: 'select',
      text: {
        hi: 'अत्यधिक कमजोरी और थकान कब से है?',
        en: 'How long have you had severe weakness and fatigue?',
        bn: 'অতিরিক্ত দুর্বলতা ও ক্লান্তি কত দিন ধরে আছে?',
        mr: 'अतिशय अशक्तपणा कधीपासून जाणवत आहे?',
        te: 'తీవ్రమైన నీరసం ఎంతకాలంగా ఉంది?',
        ta: 'கடுமையான சோர்வு எவ்வளவு காலமாக உள்ளது?',
          pa: 'How long have you had severe weakness and fatigue?',
  },
      options: [
        {
          id: 'gw_acute',
          label: {
            hi: 'अचानक आज चक्कर खाकर गिर पड़े (Syncope/Fainting)',
            en: 'Sudden collapse or fainting today (Syncope)',
            bn: 'আজ হঠাৎ মাথা ঘুরে পড়ে যাওয়া',
            mr: 'आज अचानक भोवळ येऊन पडणे',
            te: 'ఈరోజే అకస్మాత్తుగా స్పృహ తప్పి పడిపోవడం',
            ta: 'இன்று திடீரென மயங்கி விழுதல்',
                pa: 'Sudden collapse or fainting today (Syncope)',
    },
          isRedFlag: true,
        },
        {
          id: 'gw_chronic',
          label: {
            hi: 'महीनों से चलने-फिरने पर जल्दी सांस फूलना (Severe Anemia/Thyroid)',
            en: 'Gradual fatigue over months with paleness',
            bn: 'কয়েক মাস ধরে ধীরে ধীরে ক্লান্তি বৃদ্ধি',
            mr: 'काही महिन्यांपासून सतत थकवा',
            te: 'కొన్ని నెలలుగా నిరంతర నీరసం',
            ta: 'பல மாதங்களாக படிப்படியான சோர்வு',
                pa: 'Gradual fatigue over months with paleness',
    },
        },
      ],
    },
  ],

  other: [
    {
      id: 'oth_duration',
      category: 'duration',
      type: 'select',
      text: {
        hi: 'यह परेशानी कितने समय से महसूस हो रही है?',
        en: 'How long have you been experiencing this issue?',
        bn: 'এই সমস্যা কত দিন ধরে অনুভব করছেন?',
        mr: 'हा त्रास किती दिवसांपासून जाणवत आहे?',
        te: 'ఈ సమస్య ఎంతకాలంగా ఉంది?',
        ta: 'இந்த பிரச்சினை எவ்வளவு காலமாக உள்ளது?',
          pa: 'How long have you been experiencing this issue?',
  },
      options: [
        {
          id: 'oth_sudden',
          label: {
            hi: 'अचानक आज शुरू हुआ है',
            en: 'Started suddenly today',
            bn: 'আজ হঠাৎ শুরু হয়েছে',
            mr: 'आज अचानक सुरू झाला',
            te: 'ఈరోజే అకస్మాత్తుగా ప్రారంభమైంది',
            ta: 'இன்று திடீரென தொடங்கியது',
                pa: 'Started suddenly today',
    },
        },
        {
          id: 'oth_few_days',
          label: {
            hi: 'कुछ दिनों से (3-7 दिन)',
            en: 'A few days (3-7 days)',
            bn: 'কয়েক দিন ধরে',
            mr: 'काही दिवसांपासून',
            te: 'కొన్ని రోజులుగా',
            ta: 'சில நாட்களாக',
                pa: 'A few days (3-7 days)',
    },
        },
        {
          id: 'oth_months',
          label: {
            hi: 'लंबे समय से (महीनों या सालों से)',
            en: 'Longstanding (months or years)',
            bn: 'দীর্ঘদিন ধরে',
            mr: 'दीर्घकाळापासून',
            te: 'చాలా కాలంగా',
            ta: 'நீண்ட காலமாக',
                pa: 'Longstanding (months or years)',
    },
        },
      ],
    },
  ],
};
